### PR TITLE
Add Botronics to the list

### PR DESCRIPTION
**Pull request by avanmalleghem**

### CODE REVIEW

**Comment by avanmalleghem** [comment]
Someone ables to merge this branch ???

**Comment by vmayoral** [comment]
Thanks for the contribution @avanmalleghem, can you please add a few words about how you're using ROS, which version and packages?

**Comment by avanmalleghem** [comment]
@vmayoral, thanks for your feedback. I did it !

**Comment by vmayoral** [comment]
@avanmalleghem, sorry, there's a conflict now. Mind looking at that? Happy to merge afterwards.

**Comment by avanmalleghem** [comment]
@vmayoral done, thanks to merge it !

**Pull request merged**
