### PR TITLE
Add Cellula Robotics

### PR DESCRIPTION
**Pull request by njhetherington**
Cool list!

### CODE REVIEW

**Comment by vmayoral** [comment]
Thanks for the contribution @njhetherington, do you think you coud add a few words about how do you guys use ROS and which packages?

**Comment by vmayoral** [comment]
ping @njhetherington, any chance do add a few more bits?

**Comment by njhetherington** [comment]
Added some more details :)

**Comment by vmayoral** [comment]
Thanks!

**Pull request merged**
